
auth.token=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

defaults.org=demigod
defaults.project=react-native

defaults.url=https://sentry.io/
