import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import {
  IsString,
  IsNotEmpty,
  IsOptional,
  ValidateIf,
  ValidateNested,
} from 'class-validator';
import { Type } from 'class-transformer';
import { DeviceInfoDto } from './device-info.dto';

// ============================================================================
// Biometric Setup DTOs
// ============================================================================

export class BiometricSetupDto {
  @ApiProperty({
    description: 'Unique device fingerprint from DeviceInfo.getUniqueId()',
    example: 'a1b2c3d4e5f6...',
  })
  @IsString()
  @IsNotEmpty()
  deviceFingerprint: string;

  @ApiPropertyOptional({
    description: 'Human-readable device name for display',
    example: 'Samsung Galaxy S24',
  })
  @IsOptional()
  @IsString()
  deviceName?: string;

  @ApiProperty({
    description:
      'PEM-encoded RSA public key generated by react-native-biometrics. ' +
      'The private key never leaves the device hardware (Android Keystore / Secure Enclave).',
  })
  @IsString()
  @IsNotEmpty()
  publicKey: string;
}

export class BiometricSetupResponseDto {
  @ApiProperty({ description: 'Device fingerprint this public key is bound to' })
  deviceFingerprint: string;

  @ApiProperty({ description: 'ISO date when the registration expires (90 days from now)' })
  expiresAt: string;

  @ApiProperty({ example: 'Biometric login set up successfully' })
  message: string;
}

// ============================================================================
// Biometric Challenge DTOs
// ============================================================================

export class BiometricChallengeDto {
  // One of userId / email / phone is required (same pattern as LoginDto)
  @IsOptional()
  @IsString()
  @ValidateIf((o) => !o.email && !o.phone)
  userId?: string;

  @IsOptional()
  @IsString()
  @ValidateIf((o) => !o.userId && !o.phone)
  email?: string;

  @IsOptional()
  @IsString()
  @ValidateIf((o) => !o.userId && !o.email)
  phone?: string;

  @ApiProperty({ description: 'Device fingerprint whose challenge is being requested' })
  @IsString()
  @IsNotEmpty()
  deviceFingerprint: string;
}

export class BiometricChallengeResponseDto {
  @ApiProperty({ description: 'Random nonce the client must sign with its private key' })
  challenge: string;
}

// ============================================================================
// Biometric Login DTOs
// ============================================================================

export class BiometricLoginDto {
  // One of userId / email / phone is required (same pattern as LoginDto)
  @IsOptional()
  @IsString()
  @ValidateIf((o) => !o.email && !o.phone)
  userId?: string;

  @IsOptional()
  @IsString()
  @ValidateIf((o) => !o.userId && !o.phone)
  email?: string;

  @IsOptional()
  @IsString()
  @ValidateIf((o) => !o.userId && !o.email)
  phone?: string;

  @ApiProperty({ description: 'Device fingerprint — must match the one registered during setup' })
  @IsString()
  @IsNotEmpty()
  deviceFingerprint: string;

  @ApiProperty({ description: 'The challenge returned by POST /auth/biometric-challenge' })
  @IsString()
  @IsNotEmpty()
  challenge: string;

  @ApiProperty({
    description:
      'Base64-encoded RSA signature of the challenge, produced by the device Secure Enclave / Keystore',
  })
  @IsString()
  @IsNotEmpty()
  signature: string;

  @IsOptional()
  @ValidateNested()
  @Type(() => DeviceInfoDto)
  deviceInfo?: DeviceInfoDto;
}

// ============================================================================
// Biometric Revoke DTO
// ============================================================================

export class BiometricRevokeDto {
  @ApiProperty({ description: 'Device fingerprint whose biometric registration should be revoked' })
  @IsString()
  @IsNotEmpty()
  deviceFingerprint: string;
}
