/**
 * Biometric Storage Utility
 *
 * Central abstraction for secure local biometric data management.
 * Wraps react-native-keychain (secure OS storage) and react-native-biometrics
 * (hardware-bound key pair via Android Keystore / iOS Secure Enclave).
 *
 * Security model:
 * - Key pair: generated by react-native-biometrics; private key NEVER leaves the hardware.
 *   The public key is sent to the server once (setup). On every login the app signs a
 *   server-issued challenge — the server verifies the signature using the stored public key.
 * - pinHash: stored in Keychain WITHOUT biometric lock — compared locally against entered PIN.
 * - identifier (phone): stored plain for pre-filling the login field.
 *
 * PIN lockout and fingerprint attempt counts are managed externally (AsyncStorage / component state).
 */

import * as Keychain from 'react-native-keychain';
import ReactNativeBiometrics from 'react-native-biometrics';

const rnBiometrics = new ReactNativeBiometrics({ allowDeviceCredentials: true });

// ---- Keychain service namespace keys ----
const SERVICES = {
  PIN_HASH: '@forge:pin_hash',
  IDENTIFIER: '@forge:biometric_identifier',
} as const;

// ---- PIN attempt tracking key (AsyncStorage used outside, stored here as constant) ----
export const PIN_ATTEMPTS_KEY = '@forge:pin_attempts';

// ============================================================================
// Key Pair Management (Hardware-bound via Android Keystore / Secure Enclave)
// ============================================================================

/**
 * Generate a hardware-bound RSA key pair.
 * The private key never leaves the secure hardware.
 * Returns the PEM-encoded public key to register with the server.
 */
export const createBiometricKeyPair = async (): Promise<string> => {
  // Delete any existing key first to avoid conflicts
  await rnBiometrics.deleteKeys();
  const { publicKey } = await rnBiometrics.createKeys();
  return publicKey;
};

/**
 * Sign a server-issued challenge with the hardware-bound private key.
 * The OS will show a biometric prompt before signing.
 * Returns the base64-encoded signature.
 */
export const signBiometricChallenge = async (
  challenge: string,
  promptMessage = 'Verify your identity to sign in',
): Promise<string | null> => {
  try {
    const { success, signature } = await rnBiometrics.createSignature({
      promptMessage,
      payload: challenge,
    });
    return success && signature ? signature : null;
  } catch {
    return null;
  }
};

/**
 * Check whether a hardware key pair already exists on this device.
 */
export const hasBiometricKeyPair = async (): Promise<boolean> => {
  try {
    const { keysExist } = await rnBiometrics.biometricKeysExist();
    return keysExist;
  } catch {
    return false;
  }
};

// Keep this alias so the rest of the app (authStore, etc.) continues to compile
// unchanged — it now checks for the key pair instead of a Keychain token.
export const hasBiometricToken = hasBiometricKeyPair;

/**
 * Delete the local key pair (e.g. on lockout, logout, or revoke).
 */
export const deleteBiometricKeyPair = async (): Promise<void> => {
  await rnBiometrics.deleteKeys();
};

// ============================================================================
// PIN Hash (NOT biometric-locked — used for local PIN verification)
// ============================================================================

/** Simple deterministic hash with app salt.
 * NOTE: For higher security swap with react-native-quick-crypto SHA-256. */
const hashPin = (pin: string): string => {
  const SALT = 'forge_pin_v1_2026';
  let hash = 0;
  const combined = pin + SALT;
  for (let i = 0; i < combined.length; i++) {
    const char = combined.charCodeAt(i);
    hash = (hash << 5) - hash + char;
    hash |= 0;
  }
  return `ph_${Math.abs(hash).toString(16).padStart(8, '0')}_${combined.length}`;
};

/** Store the hashed PIN in Keychain (no biometric lock needed). */
export const storePinHash = async (pin: string): Promise<void> => {
  await Keychain.setGenericPassword('pin', hashPin(pin), {
    service: SERVICES.PIN_HASH,
    accessible: Keychain.ACCESSIBLE.WHEN_UNLOCKED,
  });
};

/**
 * Verify a user-entered PIN against the stored hash.
 * Returns true if correct, false otherwise.
 */
export const verifyPin = async (pin: string): Promise<boolean> => {
  try {
    const stored = await Keychain.getGenericPassword({ service: SERVICES.PIN_HASH });
    if (!stored) return false;
    return stored.password === hashPin(pin);
  } catch {
    return false;
  }
};

/** Check if a PIN hash has been stored (i.e. PIN has been set up). */
export const hasPinStored = async (): Promise<boolean> => {
  try {
    const result = await Keychain.hasGenericPassword({ service: SERVICES.PIN_HASH });
    return !!result;
  } catch {
    return false;
  }
};

/** Remove the stored PIN hash. */
export const deletePin = async (): Promise<void> => {
  await Keychain.resetGenericPassword({ service: SERVICES.PIN_HASH });
};

// ============================================================================
// Identifier Storage (phone number, for pre-filling on login screen)
// ============================================================================

export const storeIdentifier = async (identifier: string): Promise<void> => {
  await Keychain.setGenericPassword('identifier', identifier, {
    service: SERVICES.IDENTIFIER,
    accessible: Keychain.ACCESSIBLE.AFTER_FIRST_UNLOCK,
  });
};

export const getStoredIdentifier = async (): Promise<string | null> => {
  try {
    const result = await Keychain.getGenericPassword({ service: SERVICES.IDENTIFIER });
    return result ? result.password : null;
  } catch {
    return null;
  }
};

// ============================================================================
// Biometric Availability
// ============================================================================

export type BiometricType = 'TouchID' | 'FaceID' | 'Biometrics' | 'None';

export interface BiometricAvailability {
  available: boolean;
  biometryType: BiometricType;
}

/** Check if the device has biometric hardware available and enrolled. */
export const checkBiometricAvailability = async (): Promise<BiometricAvailability> => {
  try {
    const { available, biometryType } = await rnBiometrics.isSensorAvailable();
    return {
      available,
      biometryType: (biometryType as BiometricType) ?? 'None',
    };
  } catch {
    return { available: false, biometryType: 'None' };
  }
};

// ============================================================================
// Clear All (on lockout, logout with disable, or revoke from settings)
// ============================================================================

/**
 * Remove biometric key pair and PIN hash.
 * Keeps identifier so the phone field is pre-filled on next full login.
 */
export const clearAllBiometricData = async (): Promise<void> => {
  await Promise.allSettled([deleteBiometricKeyPair(), deletePin()]);
};
